# Generated by Django 3.2.25 on 2024-03-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('TimeCapsuleManagement', '0002_auto_20240311_1926'),
        ('AuthenticationSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
