# Generated by Django 5.0.3 on 2024-03-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationSystem', '0003_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
