# Generated by Django 5.0.1 on 2024-02-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationSystem', '0003_alter_userprofile_options_alter_userprofile_managers_and_more'),
        ('TimeCapsuleManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='AuthenticationSystem.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_capsules', to='AuthenticationSystem.userprofile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='AuthenticationSystem.userprofile'),
        ),
    ]
