# Generated by Django 5.0.1 on 2024-02-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCapsuleManagement', '0002_alter_capsule_owner_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='TimeCapsuleManagement.capsule'),
        ),
        migrations.CreateModel(
            name='CapsuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('text', 'Text')], max_length=20)),
                ('file', models.FileField(upload_to='capsule_content/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='TimeCapsuleManagement.capsule')),
            ],
        ),
        migrations.DeleteModel(
            name='CapsuleMedia',
        ),
    ]
